<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Product::truncate();
        ProductImage::truncate();
        Schema::enableForeignKeyConstraints();

        $products = [
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Bó Hoa Hồng Đỏ Premium',
                'slug' => 'bo-hoa-hong-do-premium',
                'description' => 'Bó 12 bông hoa hồng đỏ tuyệt đẹp, tươi tắn, thích hợp cho các dịp lãng mạn như Valentine, kỷ niệm hoặc xin lỗi.',
                'price' => 250000.00,
                'sale_price' => 200000.00,
                'stock' => 44,
                'image' => 'https://i.pinimg.com/736x/ba/9a/2a/ba9a2a9ed96da2d955037ed66e7858f0.jpg',
                'status' => 'active',
                'rating' => 4.50,
                'review_count' => 2,
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Bó Hoa Hồng Hồng Pastel',
                'slug' => 'bo-hoa-hong-hong-pastel',
                'description' => 'Bó 15 bông hoa hồng màu hồng nhạt rất nữ tính, phù hợp cho những người yêu thích vẻ đẹp nhẹ nhàng.',
                'price' => 280000.00,
                'sale_price' => null,
                'stock' => 34,
                'image' => 'https://i.pinimg.com/736x/3e/30/db/3e30dbde7837eec117024e7ffc4aa9b5.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'Bó Hoa Hồng Trắng Thanh Cao',
                'slug' => 'bo-hoa-hong-trang-thanh-cao',
                'description' => 'Bó 20 bông hoa hồng trắng tinh khiết, biểu tượng của sự thanh cao và tình yêu thuần khiết.',
                'price' => 320000.00,
                'sale_price' => 250000.00,
                'stock' => 40,
                'image' => 'https://i.pinimg.com/736x/85/85/6e/85856e8c6302f3d169c74035956b06bc.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 5,
                'category_id' => 2,
                'name' => 'Bó Hoa Huệ Trắng Sang Trọng',
                'slug' => 'bo-hoa-hue-trang-sang-trong',
                'description' => 'Bó 10 bông hoa huệ trắng cao quý, thích hợp cho các sự kiện chính thức và lễ tưởng niệm.',
                'price' => 350000.00,
                'sale_price' => 280000.00,
                'stock' => 25,
                'image' => 'https://i.pinimg.com/736x/4a/ef/46/4aef460fe45e5a7f4a4175bff70fd4a0.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 6,
                'category_id' => 2,
                'name' => 'Bó Hoa Huệ Hồng Rực Rỡ',
                'slug' => 'bo-hoa-hue-hong-ruc-ro',
                'description' => 'Bó 12 bông hoa huệ hồng sắc vivo, tỏa hương thơm nhẹ và quyến rũ. Bền lâu, thích hợp để trang trí.',
                'price' => 380000.00,
                'sale_price' => null,
                'stock' => 29,
                'image' => 'https://i.pinimg.com/736x/30/81/b4/3081b4965b0976187f35a568825d2f03.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 8,
                'category_id' => 3,
                'name' => 'Bó Hoa Tulip Đỏ Tươi',
                'slug' => 'bo-hoa-tulip-do-tuoi',
                'description' => 'Bó 15 bông hoa tulip đỏ tươi tắn, biểu tượng của tình yêu chân thành. Phù hợp cho Valentine.',
                'price' => 200000.00,
                'sale_price' => 160000.00,
                'stock' => 45,
                'image' => 'https://i.pinimg.com/736x/19/36/c8/1936c80e94871ac9b6034c82d710e207.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 9,
                'category_id' => 3,
                'name' => 'Bó Hoa Tulip Vàng Rực',
                'slug' => 'bo-hoa-tulip-vang-ruc',
                'description' => 'Bó 20 bông hoa tulip vàng tươi sáng, mang lại niềm vui và sự lạc quan cho ngày của bạn.',
                'price' => 220000.00,
                'sale_price' => null,
                'stock' => 40,
                'image' => 'https://i.pinimg.com/736x/69/f8/f3/69f8f3f590faaa613509af45d1d2c3a3.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 10,
                'category_id' => 3,
                'name' => 'Bó Hoa Tulip Tím Thanh Cao',
                'slug' => 'bo-hoa-tulip-tim-thanh-cao',
                'description' => 'Bó 18 bông hoa tulip tím sang trọng, lý tưởng để tặng những người đặc biệt trong cuộc đời bạn.',
                'price' => 240000.00,
                'sale_price' => 190000.00,
                'stock' => 35,
                'image' => 'https://i.pinimg.com/736x/4b/c5/db/4bc5db2fb7b69acb070516be9dedfa3d.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 11,
                'category_id' => 4,
                'name' => 'Bó Hoa Đơn Hương Vàng Tươi',
                'slug' => 'bo-hoa-don-huong-vang-tuoi',
                'description' => 'Bó 5 bông hoa đơn hương vàng rực rỡ, tỏa mùi thơm tự nhiên. Thích hợp để mang vui vẻ vào nhà.',
                'price' => 150000.00,
                'sale_price' => 120000.00,
                'stock' => 60,
                'image' => 'https://i.pinimg.com/736x/35/54/bd/3554bd5e9ed0bf14037b7abe3465a7f9.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 14,
                'category_id' => 5,
                'name' => 'Bó Hoa Cẩm Tú Xanh Tuyền',
                'slug' => 'bo-hoa-cam-tu-xanh-tuyen',
                'description' => 'Bó 10 bông hoa cẩm tú xanh biếc mịn màng, biểu tượng của sự bình yên và thanh bình. Bền lâu sau khi cắt.',
                'price' => 220000.00,
                'sale_price' => 180000.00,
                'stock' => 40,
                'image' => 'https://i.pinimg.com/736x/a4/d7/84/a4d784aef0ba41258ed13f3717defe5c.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 15,
                'category_id' => 5,
                'name' => 'Bó Hoa Cẩm Tú Hồng Nữ Tính',
                'slug' => 'bo-hoa-cam-tu-hong-nu-tinh',
                'description' => 'Bó 8 bông hoa cẩm tú hồng nhạt rất nữ tính, tỏa hương nhẹ nhàng. Thích hợp cho phòng ngủ và phòng khách.',
                'price' => 240000.00,
                'sale_price' => null,
                'stock' => 35,
                'image' => 'https://i.pinimg.com/736x/d5/b4/8c/d5b48c9a8cd1ece62fef123d1a2d3454.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 16,
                'category_id' => 5,
                'name' => 'Bó Hoa Cẩm Tú Tím Hoàng Gia',
                'slug' => 'bo-hoa-cam-tu-tim-hoang-gia',
                'description' => 'Bó 7 bông hoa cẩm tú tím đậm hoàng gia, rất sang trọng và ấn tượng cho bất kì không gian nào.',
                'price' => 260000.00,
                'sale_price' => 210000.00,
                'stock' => 28,
                'image' => 'https://i.pinimg.com/736x/c6/3a/60/c63a60db72d1eb9d11a320e48144c101.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 17,
                'category_id' => 6,
                'name' => 'Bó Hoa Cúc Vàng Tươi',
                'slug' => 'bo-hoa-cuc-vang-tuoi',
                'description' => 'Bó 20 bông hoa cúc vàng rực rỡ, mang ý nghĩa về sự vui vẻ và lòng trung thành. Bền lâu rất tốt.',
                'price' => 120000.00,
                'sale_price' => 90000.00,
                'stock' => 69,
                'image' => 'https://moonflowerhanoi.com/wp-content/uploads/2024/06/4.bo-hoa-chia-buon-cuc-vang-trang-vinh-hang.webp',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 18,
                'category_id' => 6,
                'name' => 'Bó Hoa Cúc Trắng Tinh Khiết',
                'slug' => 'bo-hoa-cuc-trang-tinh-khiet',
                'description' => 'Bó 18 bông hoa cúc trắng tinh khiết, biểu tượng của sự tươi mới và thanh cao. Lý tưởng cho mọi dịp.',
                'price' => 130000.00,
                'sale_price' => null,
                'stock' => 65,
                'image' => 'https://moonflowerhanoi.com/wp-content/uploads/2024/06/5.bo-hoa-dam-tang-cuc-trang-binh-yen.webp',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 19,
                'category_id' => 6,
                'name' => 'Bó Hoa Cúc Tana',
                'slug' => 'bo-hoa-cuc-tana',
                'description' => 'Bó 22 bông hoa cúc mềm mại, tỏa hương tự nhiên dễ chịu. Trang trí tốt cho phòng khách.',
                'price' => 140000.00,
                'sale_price' => 110000.00,
                'stock' => 55,
                'image' => 'https://i.pinimg.com/736x/e0/06/1a/e0061aac0c51f5f961a0c501d022bc8e.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 20,
                'category_id' => 1,
                'name' => 'Bó Hoa Hồng Mix Sang Trọng',
                'slug' => 'bo-hoa-hong-mix-sang-trong',
                'description' => 'Bó hoa hồng mix các loại hồng, trắng, và hồng nhạt được bố trí tôn lên nhau. Lựa chọn hoàn hảo cho những dịp đặc biệt.',
                'price' => 500000.00,
                'sale_price' => 400000.00,
                'stock' => 10,
                'image' => 'https://i.pinimg.com/736x/b9/42/a0/b942a09b4067ef60eb36e2eb6b9839a0.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 21,
                'category_id' => 3,
                'name' => 'Bó Hoa Tulip Kết Hợp',
                'slug' => 'bo-hoa-tulip-ket-hop',
                'description' => 'Sự kết hợp hoàn hảo giữa hoa huệ và hoa tulip, tạo nên bó hoa độc đáo và đặc biệt.',
                'price' => 380000.00,
                'sale_price' => 320000.00,
                'stock' => 18,
                'image' => 'https://i.pinimg.com/736x/4f/88/3a/4f883a4a317f3fad2dc1297257659525.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 22,
                'category_id' => 7,
                'name' => 'Bó Hoa Mix 5 Loại Đặc Biệt',
                'slug' => 'bo-hoa-mix-5-loai-dac-biet',
                'description' => 'Bó hoa mix gồm 5 loại hoa khác nhau: hồng, huệ, tulip, cẩm tú, và cúc. Được xếp thành các arrangement xinh đẹp.',
                'price' => 420000.00,
                'sale_price' => 340000.00,
                'stock' => 12,
                'image' => 'https://i.pinimg.com/736x/23/23/ff/2323ff9402867bbbe4e3b11edf04ffb8.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
            [
                'id' => 23,
                'category_id' => 4,
                'name' => 'Hoa Peonies',
                'slug' => 'hoa-peonies',
                'description' => 'Hoa peonies tròn tròn cute',
                'price' => 300000.00,
                'sale_price' => null,
                'stock' => 30,
                'image' => 'https://i.pinimg.com/736x/00/e2/a5/00e2a5c0d35a9a3ddabad454dda5c735.jpg',
                'status' => 'active',
                'rating' => 0.00,
                'review_count' => 0,
            ],
        ];

        foreach ($products as $product) {
            Product::create([
                'id' => $product['id'],
                'category_id' => $product['category_id'],
                'name' => $product['name'],
                'slug' => $product['slug'],
                'description' => $product['description'],
                'price' => $product['price'],
                'sale_price' => $product['sale_price'],
                'stock' => $product['stock'],
                'image' => $product['image'],
                'status' => $product['status'],
                'rating' => $product['rating'],
                'review_count' => $product['review_count'],
            ]);
        }

        $galleryImages = [
            [
                'product_id' => 1,
                'image' => 'https://i.pinimg.com/736x/a2/1d/a6/a21da64e0945b8d7c0d0080a3bc15f9b.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 1,
                'image' => 'https://i.pinimg.com/736x/92/5d/61/925d6173b49a25d90b733684137bdaa4.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 1,
                'image' => 'https://i.pinimg.com/736x/fc/c3/61/fcc361244f5d9b114431f777c9adf708.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 2,
                'image' => 'https://i.pinimg.com/736x/1c/c2/ff/1cc2ff455d0af03980a5d533605adcb4.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 2,
                'image' => 'https://i.pinimg.com/736x/4a/69/c3/4a69c3aa9b4db625e56378fc59144583.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 2,
                'image' => 'https://i.pinimg.com/736x/f9/d3/28/f9d32861c19e7c79e91194f7c0b28f15.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 3,
                'image' => 'https://i.pinimg.com/736x/7e/2a/b2/7e2ab2a12526b0a00435e8b47258ca77.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 3,
                'image' => 'https://i.pinimg.com/736x/48/a5/1d/48a51d59d383b6d931b77690a5c791bf.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 3,
                'image' => 'https://i.pinimg.com/736x/ef/da/79/efda7989675addaae57a258f8fd25c4e.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 5,
                'image' => 'https://i.pinimg.com/736x/67/04/e3/6704e3c92265d3f580bc01764db46966.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 5,
                'image' => 'https://i.pinimg.com/736x/e5/ed/75/e5ed75ebef7ddbb83d314a36652ca1f3.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 5,
                'image' => 'https://i.pinimg.com/736x/40/e6/bd/40e6bdeee9e8be638abcac698884cc1f.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 6,
                'image' => 'https://i.pinimg.com/736x/0c/e5/ae/0ce5ae100b172a508ec627fe7d40017d.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 6,
                'image' => 'https://i.pinimg.com/736x/91/0f/43/910f4357eb4fe4ac8e3166a195728253.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 6,
                'image' => 'https://i.pinimg.com/736x/24/9f/69/249f697d52cc5549712045faa458cb71.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 8,
                'image' => 'https://i.pinimg.com/736x/89/a5/60/89a56029635a40a3ef528d268eb92680.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 8,
                'image' => 'https://i.pinimg.com/736x/4d/ce/d9/4dced9a6e47e6da1daf0a2c19fd174a9.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 8,
                'image' => 'https://i.pinimg.com/736x/67/6f/03/676f039c30dfdaf9667fb1f1564e8934.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 9,
                'image' => 'https://i.pinimg.com/736x/52/11/60/521160ad4f60269358f5fb2c110d249f.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 9,
                'image' => 'https://i.pinimg.com/736x/d7/8a/cc/d78acc98d598f55e849c3d5058357aff.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 9,
                'image' => 'https://i.pinimg.com/736x/11/75/64/1175648e39f2a04eaf51ec9fa97a7df7.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 10,
                'image' => 'https://i.pinimg.com/736x/b2/f5/a2/b2f5a2aea28c162951dc58d22118b7cd.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 10,
                'image' => 'https://i.pinimg.com/736x/cf/f3/8e/cff38e261ca2beb74998d81dd7585317.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 10,
                'image' => 'https://i.pinimg.com/736x/8a/de/3f/8ade3f4ccd3faf3b765c82328573536f.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 11,
                'image' => 'https://i.pinimg.com/736x/4a/9b/bc/4a9bbcd3c3beffb8fef071479d7e2734.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 11,
                'image' => 'https://i.pinimg.com/736x/4d/a1/7f/4da17f17b86cf67567142c77d71057bd.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 11,
                'image' => 'https://i.pinimg.com/736x/b7/78/6f/b7786f430fbf74b595fd5fe996df8069.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 23,
                'image' => 'https://i.pinimg.com/736x/19/8f/35/198f3567b4b0cc08ad7bba38a76c3385.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 23,
                'image' => 'https://i.pinimg.com/736x/9d/2a/f5/9d2af5342b4dec2c0bbf52fd85525bf9.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 23,
                'image' => 'https://i.pinimg.com/736x/b4/a8/2c/b4a82c14bb6429477b56edc6807b002a.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 14,
                'image' => 'https://i.pinimg.com/736x/d4/05/ee/d405eecd1fb5021ea999e02554d7cc0e.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 14,
                'image' => 'https://i.pinimg.com/736x/ee/51/e3/ee51e36fbd7578c6a5220507312b4f82.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 14,
                'image' => 'https://i.pinimg.com/736x/46/78/68/4678682775f5e34f4f7cea397bb35e21.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 15,
                'image' => 'https://i.pinimg.com/736x/a1/6d/72/a16d72dba460c121149990736059a25a.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 15,
                'image' => 'https://i.pinimg.com/736x/93/76/b1/9376b16b22be6a86be4474084f9dcd1d.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 15,
                'image' => 'https://i.pinimg.com/736x/8b/9e/c0/8b9ec03c66f56b5637d4b4d817ad711d.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 16,
                'image' => 'https://i.pinimg.com/736x/e1/c6/bc/e1c6bc39c3d7595a874b9a7edcf1b033.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 16,
                'image' => 'https://i.pinimg.com/736x/45/e7/bb/45e7bb578f7a468368a7f37302cbb878.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 16,
                'image' => 'https://i.pinimg.com/736x/25/62/1c/25621c62c8593f34d6be6e1328165fb9.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 17,
                'image' => 'https://tse3.mm.bing.net/th/id/OIP.Pc_7QzXnERty48JRMphmpgHaJV?rs=1&pid=ImgDetMain&o=7&rm=3',
                'order' => 0,
            ],
            [
                'product_id' => 17,
                'image' => 'https://tse3.mm.bing.net/th/id/OIP.Pc_7QzXnERty48JRMphmpgHaJV?rs=1&pid=ImgDetMain&o=7&rm=3',
                'order' => 1,
            ],
            [
                'product_id' => 17,
                'image' => 'https://tse3.mm.bing.net/th/id/OIP.Pc_7QzXnERty48JRMphmpgHaJV?rs=1&pid=ImgDetMain&o=7&rm=3',
                'order' => 2,
            ],
            [
                'product_id' => 18,
                'image' => 'https://i.pinimg.com/originals/83/13/41/83134181a7c4f5379067248ab2a63c41.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 18,
                'image' => 'https://tse4.mm.bing.net/th/id/OIP.WUjFobpece5rBqiZiYIdLAHaJ3?w=736&h=981&rs=1&pid=ImgDetMain&o=7&rm=3',
                'order' => 1,
            ],
            [
                'product_id' => 18,
                'image' => 'https://tse4.mm.bing.net/th/id/OIP.WUjFobpece5rBqiZiYIdLAHaJ3?w=736&h=981&rs=1&pid=ImgDetMain&o=7&rm=3',
                'order' => 2,
            ],
            [
                'product_id' => 19,
                'image' => 'https://i.pinimg.com/736x/53/46/1d/53461dec6f4ba129f9aa0454d39e221a.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 19,
                'image' => 'https://i.pinimg.com/736x/6a/b9/fd/6ab9fd15110081a538c91d966c69857a.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 19,
                'image' => 'https://i.pinimg.com/736x/ca/ae/9d/caae9daa0c33904d87d3c5f1ee39b0ab.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 20,
                'image' => 'https://i.pinimg.com/736x/27/d7/a9/27d7a91ec484d732b535a35b7c128a5f.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 20,
                'image' => 'https://i.pinimg.com/736x/31/ae/8b/31ae8be7699e9c6dd561a0c0715570b0.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 20,
                'image' => 'https://i.pinimg.com/736x/dc/0d/6c/dc0d6cb38a9b31c4dad9a9449caaa13f.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 21,
                'image' => 'https://i.pinimg.com/736x/0a/3f/a8/0a3fa82c49c4205a83aa0e97a755cc16.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 21,
                'image' => 'https://i.pinimg.com/736x/b5/47/45/b547450699f3ad2d7e900b1daa51a2b1.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 21,
                'image' => 'https://i.pinimg.com/736x/bd/b1/5a/bdb15a055a375599142e9567d49666d5.jpg',
                'order' => 2,
            ],
            [
                'product_id' => 22,
                'image' => 'https://i.pinimg.com/736x/2a/49/0c/2a490caaadbd3479390203342013cd66.jpg',
                'order' => 0,
            ],
            [
                'product_id' => 22,
                'image' => 'https://i.pinimg.com/736x/b1/d9/e0/b1d9e04495c4363d1d8012c4c4078888.jpg',
                'order' => 1,
            ],
            [
                'product_id' => 22,
                'image' => 'https://i.pinimg.com/736x/39/a2/b9/39a2b91d786bb826cf7c65b143407c33.jpg',
                'order' => 2,
            ],
        ];

        foreach ($galleryImages as $image) {
            ProductImage::create([
                'product_id' => $image['product_id'],
                'image' => $image['image'],
                'order' => $image['order'],
            ]);
        }
    }
}
